### ISSUE TITLE
Implement Go vendor/ dependencies

### ISSUE THREAD

**Issue by radoondas** [radoondas/elasticbeat#10]

**Comment by radoondas** [comment]
Almost all dependencies are in, but currently struggling with glide not able to fetch all dependencies to ```vendor/``` folder, e.g.:
```
[INFO] Fetching gopkg.in/yaml.v2 into /home/rondas/workspace/go/src/github.com/radoondas/apachebeat/vendor
[ERROR] Failed to fetch gopkg.in/yaml.v2: Cannot detect VCS
```
@ruflin: did you have the same issue as I do? Maybe I'm missing an important point.

**Comment by ruflin** [comment]
@radoondas Unfortunately a known issue which should be fixed in the next glide version: https://github.com/Masterminds/glide/issues/221 @cyrilleverrier took care of it.

**Comment by radoondas** [comment]
@ruflin Thanks! I was looking for such issue, but I must have been blind this morning :)

**Comment by radoondas** [comment]
Funny!
Even with latest glide v 0.9.0-rc1 I get the same error:
```
[INFO] Fetching gopkg.in/yaml.v2 into /home/rondas/workspace/go/src/github.com/radoondas/apachebeat/vendor
[ERROR] Failed to fetch gopkg.in/yaml.v2: Cannot detect VCS
```

But! when I change glide.yml 
from:
```
- package: gopkg.in/yaml.v2
```

to:
```
- package: gopkg.in/yaml.v2
  vcs: git
```

Dependency for yaml.v2 is resolving without issues :)

**Comment by radoondas** [comment]
On the other hand, I get another one for the reference:

```
[INFO] Fetching updates for github.com/Shopify/sarama.
[WARN] Download failed.
[WARN] Error updating github.com/Shopify/sarama: exit status 1
[INFO] Setting version for github.com/Shopify/sarama to v1.8.0.
```

**Comment by ruflin** [comment]
One of the reasons why we checked in the vendor directory, because such things happen frequently. Perhaps you could use `glide update --no-recursive` so you need to download less dependencies.
