### ISSUE TITLE
Unable to import Searches/Visualizations/Dashboards in Kibana

### ISSUE THREAD

**Issue by guptayuvraj** [radoondas/elasticbeat#16]
Hi

I am unable to import either the Search or Visualization or Dashboard in Kibana as present inside the kibana/dashboard directory.

Upon opening a saved search json file (cluster-stats) having its code as:-
{
  "title": "Cluster stats",
  "description": "",
  "hits": 0,
  "columns": [
    "_type"
  ],
  "sort": [
    "@timestamp",
    "desc"
  ],
  "version": 1,
  "kibanaSavedObjectMeta": {
    "searchSourceJSON": "{\"index\":\"elasticbeat-*\",\"query\":{\"query_string\":{\"query\":\"_type:cluster_stats\",\"analyze_wildcard\":true}},\"filter\":[],\"highlight\":{\"pre_tags\":[\"@kibana-highlighted-field@\"],\"post_tags\":[\"@/kibana-highlighted-field@\"],\"fields\":{\"*\":{}},\"require_field_match\":false,\"fragment_size\":2147483647}}"
  }
}

Upon verifying with an existing saved search found few lines to be missing in the file due to which it isn't importing. Added _id,_type & _source which was then able to import into Kibana properly.
[
  {
    "_id": "Cluser-stat",
    "_type": "search",
    "_source": {
  "title": "Cluster stats",
  "description": "",
  "hits": 0,
  "columns": [
    "_type"
  ],
  "sort": [
    "@timestamp",
    "desc"
  ],
  "version": 1,
  "kibanaSavedObjectMeta": {
    "searchSourceJSON": "{\"index\":\"elasticbeat-*\",\"query\":{\"query_string\":{\"query\":\"_type:cluster_stats\",\"analyze_wildcard\":true}},\"filter\":[],\"highlight\":{\"pre_tags\":[\"@kibana-highlighted-field@\"],\"post_tags\":[\"@/kibana-highlighted-field@\"],\"fields\":{\"*\":{}},\"require_field_match\":false,\"fragment_size\":2147483647}}"
  }
}
}
]

Similarly faced problems for Visualizations & Dashboard which too were able to solve & import into Kibana in that way.

**Comment by radoondas** [comment]
@guptayuvraj Thanks for reporting issue. What version of elasticsearch do you use? Meanwhile, I'll try to replicate it locally.

**Comment by radoondas** [comment]
@guptayuvraj Additional question. Do you import visualisations directly to Kibana with import feature? If yes, then this might cause your problems. Content of the folder with visualization is meant to be imported to Elasticsearch with load.sh script as stated in the [documentation](https://github.com/radoondas/elasticbeat/blob/master/KIBANA.md).

**Comment by guptayuvraj** [comment]
Hi @radoondas Yes importing visualization directly to Kibana with import feature is causing problems. For beginners can we directly provide them json files which can be directly imported to Kibana? Also it requires load.sh file to be downloaded separately. 
If possible let's keep both the options ready where via script you can use when you have a secured ES cluster requiring username & password among various other options.
If they want to use the dashboards directly they can import from the file present in repository.

If yes I have updated the changes & can send you a pull request for the same.

**Comment by guptayuvraj** [comment]
Hi @radoondas  Facing issue while using load.sh script as mentioned by you in Kibana simple Guide.

Error faced as following:-

yuvraj@ubuntu:~/go/src/github.com/radoondas/elasticbeat$ ./load.sh -url http://localhost:9200 
Loading dashboards to http://localhost:9200 in .kibana
{"error":{"root_cause":[{"type":"index_already_exists_exception","reason":"already exists","index":".kibana"}],"type":"index_already_exists_exception","reason":"already exists","index":".kibana"},"status":400}{"acknowledged":true}Loading search *:
./load.sh: line 109: dashboards/search/tmp_search.json: No such file or directory
Warning: Couldn't read data from file "dashboards/search/tmp_search.json", 
Warning: this makes an empty POST.
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse, document is empty"}],"type":"mapper_parsing_exception","reason":"failed to parse, document is empty"},"status":400}
rm: cannot remove ‘dashboards/search/tmp_search.json’: No such file or directory
Loading visualization *:
Warning: Couldn't read data from file "dashboards/visualization/*.json", this 
Warning: makes an empty POST.
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse, document is empty"}],"type":"mapper_parsing_exception","reason":"failed to parse, document is empty"},"status":400}
Loading dashboard *:
Warning: Couldn't read data from file "dashboards/dashboard/*.json", this 
Warning: makes an empty POST.
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse, document is empty"}],"type":"mapper_parsing_exception","reason":"failed to parse, document is empty"},"status":400}
awk: cannot open dashboards/index-pattern/*.json (No such file or directory)
Loading index pattern :
Warning: Couldn't read data from file "dashboards/index-pattern/*.json", this 
Warning: makes an empty POST.
No handler found for uri [/.kibana/index-pattern/] and method [PUT]

**Comment by radoondas** [comment]
@guptayuvraj sorry for being late with update. 
1, First, it seems that you have already all of the visualizations in your index.  Current version of the script expects that .kibana has no such objects already indexed.
Try it please with .kibana without objects already indexed.

2, Script have to be updated with little check for this error: 
_rm: cannot remove ‘dashboards/search/tmp_search.json’: No such file or directory_
I'll update the script and create PR for it.

3, I'll try to reproduce errors:
_Warning: Couldn't read data from file "dashboards/dashboard/.json", this
Warning: makes an empty POST._

**Comment by radoondas** [comment]
@guptayuvraj I have observed your error and found out what you have done. 
The issue you had is while importing visualizations is that you were outside of the folder kibana. When importing, you have to change directory to 'kibana'. In the guide you can see following line:
```
cd ~/workspace/go/src/github.com/radoondas/elasticbeat/kibana
```

I am closing this issue now.
