### ISSUE TITLE
Please create a Guide on installing elasticbeat on Windows

### ISSUE THREAD

**Issue by guptayuvraj** [radoondas/elasticbeat#19]
Kindly create a installation guide mentioning various steps in order to install elasticbeat on Windows.

**Comment by radoondas** [comment]
Thanks for bringing it up. It has a little lower priority now, but general 'go build' with correct environment variables should work without issues.

**Comment by guptayuvraj** [comment]
Hi @radoondas 
I built the go package using go build which created an executable file named elasticbeat.exe .
However on running it, getting following error:-

json:cannot unmarshal number -1 into Go value of type uint64.

go version installed is:- go version go1.6.2 windows/amd64

**Comment by radoondas** [comment]
Thanks for trying! This is bug. Elasticbeat expects undigned integer as value. Could you please run it eith -d "*" to see, which value in elasticbeat is -1? 
Or run all 3 commanda from README file to get current output when this hapens.

**Comment by guptayuvraj** [comment]
Please find the output of the above command mentioned by you:-

C:\Go\src\github.com\radoondas\elasticbeat>elasticbeat.exe -d "*" -e -v -c elasticbeat.yml with-d "*"
2016/05/19 02:23:03.009149 beat.go:196: INFO Home path: [C:\Go\src\github.com\radoondas\elasticbeat] Config path: [C:\Go\src\github.com\radoondas\elasticbeat] Data path: [C:\Go\src\github.com\radoondas\elasticbeat\data] Logs path: [C:\Go\src\github.com\radoondas\elasticbeat\logs]
2016/05/19 02:23:03.016155 filter.go:41: DBG  configuration []
2016/05/19 02:23:03.017155 filter.go:52: DBG  filters:
2016/05/19 02:23:03.018161 beat.go:202: DBG  Filters:
2016/05/19 02:23:03.020157 elasticbeat.go:92: DBG  Init elasticbeat
2016/05/19 02:23:03.021157 elasticbeat.go:93: DBG  Period 10s
2016/05/19 02:23:03.023162 elasticbeat.go:94: DBG  Watch [http://127.0.0.1:9200/]
2016/05/19 02:23:03.025161 elasticbeat.go:95: DBG  Nodes statistics true
2016/05/19 02:23:03.027164 elasticbeat.go:96: DBG  Cluster statistics true
2016/05/19 02:23:03.029165 elasticbeat.go:97: DBG  Cluster health statistics true
2016/05/19 02:23:03.030166 beat.go:225: INFO Setup Beat: elasticbeat; Version: 5.0.0-SNAPSHOT
2016/05/19 02:23:03.032167 beat.go:227: DBG  Initializing output plugins
2016/05/19 02:23:03.034167 geolite.go:24: INFO GeoIP disabled: No paths were set under shipper.geoip.paths
2016/05/19 02:23:03.037169 client.go:452: DBG  ES Ping(url=http://localhost:9200, timeout=1m30s)
2016/05/19 02:23:03.046179 client.go:461: DBG  Ping status code: 200
2016/05/19 02:23:03.048177 outputs.go:88: INFO Activated elasticsearch as output plugin.
2016/05/19 02:23:03.052184 publish.go:236: DBG  Create output worker
2016/05/19 02:23:03.055182 publish.go:278: DBG  No output is defined to store the topology. The server fields might not be filled.
2016/05/19 02:23:03.058187 publish.go:292: INFO Publisher name: XE-T-YGUPTA
2016/05/19 02:23:03.090764 async.go:63: INFO Flush Interval set to: 1s
2016/05/19 02:23:03.093229 async.go:64: INFO Max Bulk Size set to: 50
2016/05/19 02:23:03.096766 async.go:72: DBG  create bulk processing worker (interval=1s, bulk size=50)
2016/05/19 02:23:03.099767 beat.go:253: INFO elasticbeat start running.
2016/05/19 02:23:03.102268 elasticbeat.go:109: DBG  Run elasticbeat
2016/05/19 02:23:03.100767 service_windows.go:51: DBG  Windows is interactive: true
2016/05/19 02:23:13.108501 elasticbeat.go:127: DBG  Cluster stats for url: http://127.0.0.1:9200/
2016/05/19 02:23:13.134019 elasticbeat.go:132: DBG  Cluster stats detail: {Timestamp:1463624593132 Cluster_name:elasticsearch Status:yellow Status_num:1 Indices:{Count:3 Shards:{Total:11 Primaries:11 Replication:0 Index:{Shards:{Min:1 Max:5 Avg:3.6666666666666665} Primaries:{Min:1 Max:5 Avg:3.6666666666666665} Replication:{Min:0 Max:0 Avg:0}}} Docs:{Count:1082 Deleted:17} Store:{Size_in_bytes:1265258 Throttle_time_in_millis:0} Fielddata:{Memory_size_in_bytes:0 Evictions:0} Query_cache:{Memory_size_in_bytes:0 Total_count:0 Hit_count:0 Miss_count:0 Cache_size:0 Cache_count:0 Evictions:0} Completion:{Size_in_bytes:0} Segments:{Count:44 Memory_in_bytes:310360 Terms_memory_in_bytes:218016 Stored_fields_memory_in_bytes:13712 Term_vectors_memory_in_bytes:0 Norms_memory_in_bytes:33280 Doc_values_memory_in_bytes:45352 Index_writer_memory_in_bytes:0 Index_writer_max_memory_in_bytes:5632000 Version_map_memory_in_bytes:0 Fixed_bit_set_memory_in_bytes:0} Percolate:{Total:0 Time_in_millis:0 Current:0 Memory_size_in_bytes:-1 Memory_size:-1b Queries:0}} Nodes:{Count:{Total:1 Master_only:0 Data_only:0 Master_data:1 Client:0} Os:{Available_processors:4 Allocated_processors:4 Mem:{Total_in_bytes:0}} Process:{Cpu:{Percent:0} Open_file_descriptors:{Min:-1 Max:-1 Avg:0}} Jvm:{Max_uptime_in_millis:34119346 Mem:{Heap_used_in_bytes:76919232 Heap_max_in_bytes:954728448} Threads:50} Fs:{Total_in_bytes:289837936640 Free_in_bytes:130030235648 Available_in_bytes:130030235648 Spins:}}}
2016/05/19 02:23:13.188095 client.go:171: DBG  Publish: {
  "@timestamp": "2016-05-19T02:23:13.187Z",
  "beat": {
    "hostname": "XE-T-YGUPTA",
    "name": "XE-T-YGUPTA"
  },
  "cluster_stats": {
    "Indices": {
      "Completion": {
        "size_in_bytes": 0
      },
      "Docs": {
        "count": 1082,
        "deleted": 17
      },
      "Fielddata": {
        "evictions": 0,
        "memory_size_in_bytes": 0
      },
      "Percolate": {
        "current": 0,
        "memory_size": "-1b",
        "memory_size_in_bytes": -1,
        "queries": 0,
        "time_in_millis": 0,
        "total": 0
      },
      "Query_cache": {
        "cache_count": 0,
        "cache_size": 0,
        "evictions": 0,
        "hit_count": 0,
        "memory_size_in_bytes": 0,
        "miss_count": 0,
        "total_count": 0
      },
      "Segments": {
        "count": 44,
        "doc_values_memory_in_bytes": 45352,
        "fixed_bit_set_memory_in_bytes": 0,
        "index_writer_max_memory_in_bytes": 5.632e+06,
        "index_writer_memory_in_bytes": 0,
        "memory_in_bytes": 310360,
        "norms_memory_in_bytes": 33280,
        "stored_fields_memory_in_bytes": 13712,
        "term_vectors_memory_in_bytes": 0,
        "terms_memory_in_bytes": 218016,
        "version_map_memory_in_bytes": 0
      },
      "Shards": {
        "Index": {
          "Primaries": {
            "avg": 3.6666666666666665,
            "max": 5,
            "min": 1
          },
          "Replication": {
            "avg": 0,
            "max": 0,
            "min": 0
          },
          "Shards": {
            "avg": 3.6666666666666665,
            "max": 5,
            "min": 1
          }
        },
        "primaries": 11,
        "replication": 0,
        "total": 11
      },
      "Store": {
        "size_in_bytes": 1.265258e+06,
        "throttle_time_in_millis": 0
      },
      "count": 3
    },
    "Nodes": {
      "Count": {
        "client": 0,
        "data_only": 0,
        "master_data": 1,
        "master_only": 0,
        "total": 1
      },
      "Fs": {
        "available_in_bytes": 1.30030235648e+11,
        "free_in_bytes": 1.30030235648e+11,
        "spins": "",
        "total_in_bytes": 2.8983793664e+11
      },
      "Jvm": {
        "Mem": {
          "heap_max_in_bytes": 9.54728448e+08,
          "heap_used_in_bytes": 7.6919232e+07
        },
        "max_uptime_in_millis": 3.4119346e+07,
        "threads": 50
      },
      "Os": {
        "Mem": {
          "total_in_bytes": 0
        },
        "allocated_processors": 4,
        "available_processors": 4
      },
      "Process": {
        "Cpu": {
          "percent": 0
        },
        "Open_file_descriptors": {
          "avg": 0,
          "max": -1,
          "min": -1
        }
      }
    },
    "cluster_name": "elasticsearch",
    "status": "yellow",
    "status_num": 1,
    "timestamp": 1.463624593132e+12
  },
  "type": "cluster_stats",
  "url": "http://127.0.0.1:9200/"
}
2016/05/19 02:23:13.239685 elasticbeat.go:146: DBG  Nodes stats for url: http://127.0.0.1:9200/
2016/05/19 02:23:13.261700 nodes.go:309: DBG  Node ids: [TYJoj2QJSpqyoGdNnYy2lg]

Observing -1 value for following fields (present in command _cluster/stats):-
**"memory_size_in_bytes":-1
"memory_size":"-1b"
"open_file_descriptors":{"min":-1,"max":-1,"avg":0}**

Observing -1 value for following fields (present in command _nodes):-
**"load_average":-1.0
"open_file_descriptors":-1
"max_file_descriptors":-1**

PS:- Upon making following changes in elasticbeat.yml, I am able to run the elasticbeat in Windows:-
  stats:
    cluster: false
    nodes: false
    health: true

**Comment by radoondas** [comment]
@guptayuvraj Thanks for your tests. I appreciate it a lot! It is clear that when you disabled cluster and nodes that it works.
As I supposed, on windows, elasticsearch put different values in to output. 

I have prepared fix. Could you please checkout branch **windows_integer_fix** and try to build and run? I have currently no possibilities to test this on Windows box.
After your test is successful, and it passes also my local tests, I can merge it to master branch.

**Comment by guptayuvraj** [comment]
Hi @radoondas 
Upon checking out latest branch of windows_integer_fix, I am unable to build. Upon entering command of go build, gives following error:-

# github.com/radoondas/elasticbeat-windows_integer_fix
.\main.go:13: cannot use beater.New() (type *beater.Elasticbeat) as type "github.com/radoondas/elasticbeat-windows_integer_fix/vendor/github.com/elastic/beats/libbeat/beat".Beater in argument to "github.com/radoondas/elasticbeat-windows_integer_fix/vendor/github.com/elastic/beats/libbeat/beat".Run:
        *beater.Elasticbeat does not implement "github.com/radoondas/elasticbeat-windows_integer_fix/vendor/github.com/elastic/beats/libbeat/beat".Beater (wrong type for Cleanup method)
                have Cleanup(*"github.com/radoondas/elasticbeat/vendor/github.com/elastic/beats/libbeat/beat".Beat) error
                want Cleanup(*"github.com/radoondas/elasticbeat-windows_integer_fix/vendor/github.com/elastic/beats/libbeat/beat".Beat) error

This error is not seen while building master branch.

**Comment by guptayuvraj** [comment]
Hi @radoondas 

The branch is working perfectly on Windows :)

**Comment by guptayuvraj** [comment]
Hi @radoondas 
can you please make one more change?
Can you please rename the file name under kibana/dashboards/dashboard from Cluster-view.json to Elasticbeat-Dashboard.json.
Also kindly rename the title under the same file from Cluster-view to Elasticbeat Dashboard.

Reason: If anyone loads the sample dashboard, then he can easily find the dashboard in Kibana by name of Elasticbeat Dashboard.

**Comment by radoondas** [comment]
@guptayuvraj Thanks for your test. I'll finish my local tests and perform merge.

For your second request I'll create another issue, for tracking it.

**Comment by prerakpshah** [comment]
@guptayuvraj : Can you assist me on how you built this on windows ? I will really appreciate your help on it. If you can put a step by step instructions.

**Comment by radoondas** [comment]
@guptayuvraj @prerakpshah if you ever create a simple guide for windows based on your steps, feel free to create PR or send me steps and I'll do the rest :) I will by glad to accept your help with documentation. Thanks

**Comment by guptayuvraj** [comment]
@radoondas @prerakpshah I will create a step by step simple guide for Installing elasticbeat on Windows. Will either create a PR or send you the steps. Will share it later today.

**Comment by prerakpshah** [comment]
Thanks @guptayuvraj. I will wait for it to be ready.

**Comment by guptayuvraj** [comment]
@prerakpshah Please follow the Windows run guide to run elasticbeat. It will help in validating the Windows Installation. 

@radoondas :- Kindly have a look and make structure/formatting changes as required. Created an in-depth guide so that anyone who is new to GO can directly use it and get up and running with elasticbeat.

I have created a Pull Request - Issue 19 which contains the file RUN_Windows.md.

**Comment by radoondas** [comment]
@guptayuvraj Thanks again, see my comment in your PR.

**Comment by radoondas** [comment]
@guptayuvraj Thanks for contribution. I am closing this with radoondas/elasticbeat/pull/25
