### ISSUE TITLE
Index pattern folder does not contain a file (When downloading repository - Windows)

### ISSUE THREAD

**Issue by guptayuvraj** [radoondas/elasticbeat#20]
When downloading repository from Github site, the repository contains all files except one file i.e. elasticbeat-*.json present inside elasticbeat/kibana/dashboards/index-pattern.

Possible Problem:- In Windows you cannot use * in file name. 

Possible Solution:- kindly rename the filename to elasticbeat.json.

PS: I am unsure whether the suggested solution will work but just an idea.

**Comment by radoondas** [comment]
Thanks @guptayuvraj. Renaming will work. I will be glad to fix it.

**Comment by radoondas** [comment]
@guptayuvraj Could you please test this if you have some time? Thanks a lot!

**Comment by guptayuvraj** [comment]
Hi @radoondas 
I am now able to view the file post renaming it :)

**Comment by radoondas** [comment]
@guptayuvraj Thanks for testing it!
