### ISSUE TITLE
Make cpu_percent signed integer

### ISSUE THREAD

**Issue by saeppl89** [radoondas/elasticbeat#29]
On some servers elasticsearch is not able to read cpu-usage, wich results in **-1** as cpu_percent-value.
The value ist stored as uint64 and should be changed to a signed integer. Otherwise you will run into errors while processing the json response.

**Comment by radoondas** [comment]
Thanks @saeppl89 for reporting! 
I will change this one. 
Just to be sure, do you mean node stats and: **Process.cpu.percent**?

Out of curiosity. Which OS/version did you detect it?

**Comment by saeppl89** [comment]
Yes, it's **Process.cpu.percent** (cluster.go:127;nodes.go:48)
We are running Elasticsearch 2.3.3 on Windows Server 2012 R2 with Xeon E5-2620 v3

**Comment by radoondas** [comment]
@saeppl89  thanks again for reporting.
I have noticed that some values for ES on Windows are '-1' when not available and I have fixed some of them in past.
Let's see how much more will be discovered :)
