### ISSUE TITLE
Refactor beats to match model from beat-generator and exit param 

### ISSUE THREAD

**Issue by radoondas** [radoondas/elasticbeat#7]
Ref - elastic/beats#864

**Comment by radoondas** [comment]
@ruflin: would you mind to have a look if I got it right? all my tests and functionality is working perfectly. Hope, I didn't overlook anything. Thanks a lot for your time. :)

**Comment by ruflin** [comment]
@radoondas LGTM. I would recommend to also update the Makefile with the reference to the libbeat Makefile. This will make the generation of the elasticbeat.yml file easy (and other functions are directly available).

**Comment by radoondas** [comment]
@ruflin Thanks a lot! I'll also reflect Makefile changes. Thanks for the point.
